# General
import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

# Set theme
[window]
padding.x = 0
padding.y = 0
decorations = "none"
startup_mode = "Maximized"

opacity = 1.0
dynamic_title = true
blur = true

[font]
# normal.family = "JuliaMono"
# normal.family = "FiraMonoNerdFont"
# normal.family = "MesloLGSNerdFont"
# normal.family = "CascadiaMono" -- really want a nerd fond
# normal.family = "CaskaydiaMonoNerdFont"
# normal.family = "JetBrainsMonoNerdFont"
# normal.family = "IosevkaNerdFont"
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
bold = { family = "JetBrainsMonoNerdFont", style = "Bold" }
italic = { family = "JetBrainsMonoNerdFont", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNerdFont", style = "Bold Italic" }
size = 12

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Off"
vi_mode_style = { shape = "Block", blinking = "Never" } 

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", action = "PasteSelection" },
    { mouse = "Middle", action = "PasteSelection" },
]
