[window]
padding.x = 0
padding.y = 0

decorations = "none"
startup_mode = "Maximized"

opacity = 0.90
blur = true

[font]
# normal.family = "JetBrains"

size = 11

# Colors (Ayu Dark)

# Default colors
[colors.primary]
background = '0x000000'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'



#[colors]
#  [colors.primary]
#    background = '0x000000'
#    foreground = '0xffffff'
