return {}
--return {
--  'obsidian-nvim/obsidian.nvim',
--  version = '*', -- use latest release, remove to use latest commit
--  ft = 'markdown',
--  ---@module 'obsidian'
--  ---@type obsidian.config
--  opts = {
--    legacy_commands = false,
--    workspaces = {
--      {
--        name = 'personal',
--        path = '/home/stephan/Documents/Obsidian/personal',
--      },
--      {
--        name = 'work',
--        path = '/home/stephan/Documents/Obsidian/work',
--      },
--    },
--  },
--}
